# FROM openjdk:8-jre

FROM bigtruedata/scala:2.11.11

#FROM docker-alpine-scala
# CHECK: 2.11.8
MAINTAINER Alfredo Serafini <seralf@gmail.com>


# ENV MAVEN_HOME ~/.m2
# ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
# VOLUME "$USER_HOME_DIR/.m2"


# Add Maven dependencies (not shaded into the artifact; Docker-cached)
ADD target/libs /usr/share/katalod/lib

ENV CLASSPATH=/usr/share/katalod/lib/*

# Add the service itself
ARG JAR_FILE
ADD target/${JAR_FILE} /usr/share/katalod/kataLOD-0.0.1.jar

ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/katalod/kataLOD-0.0.1.jar"]


CMD []