# QUERY FOR SKOS!
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX clvapit: <http://dati.gov.it/onto/clvapit#>
SELECT DISTINCT ?uri ?group 
WHERE {
	?uri a skos:Concept .
	?uri skos:broader* ?group .
	OPTIONAL { ?group clvapit:hasRankOrder ?rank . }
}
ORDER BY ?uri ?rank